// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsZX5M1jmeQ5AbOJKYH3qWnwAxdy9VwY',
    appId: '1:777818017067:web:108fb6dc03fb29d07ac96e',
    messagingSenderId: '777818017067',
    projectId: 'teste-teste-a8d80',
    authDomain: 'teste-teste-a8d80.firebaseapp.com',
    storageBucket: 'teste-teste-a8d80.appspot.com',
    measurementId: 'G-QJ1MYJ2HDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdco0oHqOMgolubNVXT7a8LrPkn7OLo0',
    appId: '1:777818017067:android:7dddace68e8f9f0a7ac96e',
    messagingSenderId: '777818017067',
    projectId: 'teste-teste-a8d80',
    storageBucket: 'teste-teste-a8d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3pxodaBCK0MrbpPbsgugGJFyUph3qSM',
    appId: '1:777818017067:ios:7126150519b795997ac96e',
    messagingSenderId: '777818017067',
    projectId: 'teste-teste-a8d80',
    storageBucket: 'teste-teste-a8d80.appspot.com',
    iosClientId: '777818017067-c0fp6r65b5t5phitpfpg97lukmi3j6ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeCatalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu3pxodaBCK0MrbpPbsgugGJFyUph3qSM',
    appId: '1:777818017067:ios:7126150519b795997ac96e',
    messagingSenderId: '777818017067',
    projectId: 'teste-teste-a8d80',
    storageBucket: 'teste-teste-a8d80.appspot.com',
    iosClientId: '777818017067-c0fp6r65b5t5phitpfpg97lukmi3j6ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeCatalogo',
  );
}
